# -*- coding: utf-8 -*-
"""pro 131.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IP0abUD5yqnfM7B3LB8Cdb-77HGVQbtS
"""

import pandas as pd

df = pd.read_csv("cleaned_data.csv")

print(df.columns)

df.drop('Unnamed: 0',axis=1,inplace=True)

df.dtypes

print(df)

df['Radius']=df['Radius'].apply(lambda x: x.replace('$', '').replace(',', '')).astype('float')

df.dtypes

df["Radius"] = df["Radius"]*6.957e+8

df['Mass']=df['Mass']*1.989e+30
gravity =[]

G = 6.67*10e-11
mass = df["Mass"]
radius = df["Radius"]
G = 6.674e-11
for index in range(0,len(mass)):
  g= (mass[index]*G)/((radius[index])**2)
  gravity.append(g)
df["Gravity"] = gravity

print(df)

df.to_csv("star_with_gravity.csv")